// Build: bundle ELK into one file, generate src/embed.generated.ts with all
// assets inlined, then compile the standalone windows-x64 binary with bun.
// Run: bun run build
// Version is injected via MMDX_VERSION (CI sets it from the git tag).

import { $ } from 'bun';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = import.meta.dir + '/..';
const read = (p: string): string => fs.readFileSync(path.join(ROOT, p), 'utf8');

// 1. ELK → single self-contained ESM bundle
const elkEntry = 'node_modules/@mermaid-js/layout-elk/dist/mermaid-layout-elk.esm.min.mjs';
const built = await Bun.build({
  entrypoints: [path.join(ROOT, elkEntry)],
  target: 'browser',
  format: 'esm',
  minify: true,
});
const elkJs = await built.outputs[0].text();
fs.mkdirSync(path.join(ROOT, 'vendor'), { recursive: true });
await Bun.write(path.join(ROOT, 'vendor/elk.bundle.mjs'), elkJs);

// 2. mermaid UMD stays as-is
fs.copyFileSync(
  path.join(ROOT, 'node_modules/mermaid/dist/mermaid.min.js'),
  path.join(ROOT, 'vendor/mermaid.min.js'),
);

// 3. font → base64
const fontPath = path.join(ROOT, 'assets/fonts/NotoSansSC-Subset.woff2');
const fontB64 = fs.existsSync(fontPath) ? Buffer.from(fs.readFileSync(fontPath)).toString('base64') : null;

// 4. version from tag (CI) or default
const buildVersion = process.env.MMDX_VERSION ?? null;

// 5. generated embed module
const generated =
  `// AUTO-GENERATED by scripts/build.ts — do not edit.\n` +
  `export const MERMAID_JS = ${JSON.stringify(read('vendor/mermaid.min.js'))};\n` +
  `export const ELK_JS = ${JSON.stringify(elkJs)};\n` +
  `export const FONT_B64 = ${JSON.stringify(fontB64)};\n` +
  `export const BUILD_VERSION = ${JSON.stringify(buildVersion)};\n`;
fs.writeFileSync(path.join(ROOT, 'src/embed.generated.ts'), generated);

// 6. compile the standalone windows-x64 binary (svgo/browser bundles cleanly)
fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
await $`bun build ${path.join(ROOT, 'src/cli.ts')} --compile --target=bun-windows-x64 --outfile ${path.join(ROOT, 'dist/mmdx-windows-x64.exe')}`;
console.log('built dist/mmdx-windows-x64.exe');
